"""Import-safe Stage 1A reproduction configuration."""

from cfsus.reproduction.config import (
    OFFICIAL_ATTRIBUTION_PROMPT,
    OFFICIAL_INTERVENTION_PROMPT,
    OFFICIAL_MODEL_ID,
    OFFICIAL_MODEL_REVISION,
    OFFICIAL_TRANSCODER_ID,
    OFFICIAL_TRANSCODER_REVISION,
    OFFICIAL_UPSTREAM_REVISION,
    ArtifactPaths,
    AssetPolicy,
    AttributionConfig,
    BackendName,
    ConfigDependencyError,
    DeviceName,
    DTypeName,
    FeatureCoordinates,
    InterventionConfig,
    OffloadName,
    PinnedAsset,
    PinnedUpstream,
    RuntimeConfig,
    SeedConfig,
    Stage1AConfig,
    Stage1AConfigError,
    load_stage1a_config,
)

__all__ = [
    "OFFICIAL_ATTRIBUTION_PROMPT",
    "OFFICIAL_INTERVENTION_PROMPT",
    "OFFICIAL_MODEL_ID",
    "OFFICIAL_MODEL_REVISION",
    "OFFICIAL_TRANSCODER_ID",
    "OFFICIAL_TRANSCODER_REVISION",
    "OFFICIAL_UPSTREAM_REVISION",
    "ArtifactPaths",
    "AssetPolicy",
    "AttributionConfig",
    "BackendName",
    "ConfigDependencyError",
    "DTypeName",
    "DeviceName",
    "FeatureCoordinates",
    "InterventionConfig",
    "OffloadName",
    "PinnedAsset",
    "PinnedUpstream",
    "RuntimeConfig",
    "SeedConfig",
    "Stage1AConfig",
    "Stage1AConfigError",
    "load_stage1a_config",
]
